services:
  api:
    build: ./py_api
    image: knharivignesh/hackathon:flask-app
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis-server:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-server:6379/0
      - OPEN_AI_KEY=key
    volumes:
      - ./py_api:/py_api
    ports:
      - "8000:8000"
    depends_on:
      - redis-server
      - celery

  redis-server:
    image: "redis:alpine"
    restart: always
    command: redis-server
    ports:
      - "6379:6379"

  celery:
    build: ./py_api
    command: celery -A run worker --loglevel INFO
    restart: always
    image: knharivignesh/hackathon:celeryapp
    environment:
      - CELERY_BROKER_URL=redis://redis-server:6379
      - CELERY_RESULT_BACKEND=redis://redis-server:6379
      - OPEN_AI_KEY=key
    depends_on:
      - redis-server
    volumes:
      - ./py_api:/py_api

  # Before running this run the command sh start.sh inside UI folder
  resume-ui:
    image: knharivignesh/hackathon:resumeui
    restart: always
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prod-nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - resume-ui
